name: windart
description: Windows API (Win32) bindings for Dart using FFI.
version: 0.1.1
repository: https://github.com/bamsen04/windart
homepage: https://github.com/bamsen04/windart
issue_tracker: https://github.com/bamsen04/windart/issues

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  ffi: ^2.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

platforms:
  windows:
